import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

test("mobile PWA contains chat, create, approval and settings surfaces without provider secrets", () => {
  const root = path.resolve("apps/mobile");
  const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
  const js = fs.readFileSync(path.join(root, "app.js"), "utf8");
  const css = fs.readFileSync(path.join(root, "styles.css"), "utf8");
  const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.webmanifest"), "utf8"));
  assert.match(html, /会话/);
  assert.match(html, /新对话/);
  assert.match(html, /审批/);
  assert.match(html, /我的/);
  assert.match(html, /id="model-select"/);
  assert.match(html, /id="new-attachment-input"[^>]*multiple/);
  assert.match(html, /id="new-attach-control"/);
  assert.match(html, /id="attachment-input"[^>]*multiple/);
  assert.match(html, /id="attachment-viewer"/);
  assert.match(html, /id="attachment-viewer-done"/);
  assert.match(html, /id="attachment-viewer-open"/);
  assert.match(html, /关闭预览/);
  assert.match(html, /id="session-approval-inbox"/);
  assert.match(html, /id="session-queue"/);
  assert.match(html, /id="goal-panel"/);
  assert.match(html, /id="session-switcher"/);
  assert.match(html, /id="open-session-switcher"/);
  assert.match(html, /id="continue-current-session"/);
  assert.match(html, /选择工作目录/);
  assert.match(html, /新建文件夹/);
  assert.match(html, /id="open-model-sheet" class="runtime-shortcut"/);
  assert.match(js, /\/mobile\/v1\/sessions/);
  assert.match(js, /\/mobile\/v1\/workspaces\/browse/);
  assert.match(js, /\/mobile\/v1\/workspaces\/directories/);
  assert.match(js, /renderRuntimeShortcut/);
  assert.match(js, /下一轮生效|将在下一轮生效/);
  assert.match(js, /rename|archive|fork/);
  assert.match(js, /connectEvents/);
  assert.match(js, /scheduleFinalReconcile/);
  assert.doesNotMatch(js, /detailSyncTimer|setInterval\(\(\)\s*=>\s*\{\s*if\s*\(current/);
  assert.match(js, /正在发送/);
  assert.match(js, /发送失败/);
  assert.match(js, /input\.blur\(\)/);
  assert.match(js, /scheduleStreamingRichText/);
  assert.match(js, /if \(streamingRenderTimers\.has\(node\)\) return/);
  assert.doesNotMatch(js, /body\.textContent = last\.dataset\.raw/);
  assert.match(js, /class="me /);
  assert.match(js, /class="ai /);
  assert.match(js, /class="think"/);
  assert.match(js, /<b>思考摘要<\/b>/);
  assert.match(js, /class="work-group status-/);
  assert.match(js, /class="\$\{rowClass\}/);
  assert.match(js, /function workHeadHtml/);
  assert.match(js, /function renderPlanCard/);
  assert.match(js, /function parseEditPatch/);
  assert.match(js, /function renderDiffCard/);
  assert.match(js, /isPlanToolMessage/);
  assert.match(js, /function renderSessionQueue/);
  assert.match(js, /function renderGoalPanel/);
  assert.match(css, /\.goal-card\{/);
  assert.match(js, /data-queue-edit/);
  assert.match(js, /data-queue-cancel/);
  assert.match(js, /data-queue-resume/);
  assert.match(js, /queue\/resume/);
  assert.match(js, /clearQueue/);
  assert.match(css, /\.session-queue\{/);
  assert.match(css, /\.chat-header\{position:fixed/);
  assert.match(css, /--chat-header-height/);
  assert.match(js, /toolActivitySummary/);
  assert.match(js, /检查 \$\{counts\.read\} 个文件/);
  assert.match(js, /\$\{counts\.search\} 次搜索/);
  assert.match(js, /运行 \$\{counts\.command\} 个命令/);
  assert.match(js, /function buildConversationTurns/);
  assert.match(js, /function groupWorkByPhase/);
  assert.match(js, /function summarizeWork/);
  assert.match(js, /class="conversation-turn/);
  assert.match(js, /\[data-tool-id="/);
  assert.match(js, /const rowClass = `tl/);
  assert.match(js, /<button class="work-head"/);
  assert.match(css, /\.tl-detail\{display:none/);
  assert.match(css, /\.work-items\{/);
  assert.match(css, /\.work-head\{/);
  assert.match(css, /\.tl-row\{/);
  assert.match(css, /\.term-cmd\{/);
  assert.match(css, /\.diff-head\{/);
  assert.match(css, /\.plan-card\{/);
  assert.match(css, /\.plan-progress-pill\{/);
  assert.match(js, /currentIndex \+ 1/);
  assert.match(js, /点击查看全部计划/);
  assert.match(css, /\.tl-state \.badge\{/);
  assert.match(js, /richTextCache/);
  assert.match(js, /instant: true/);
  assert.match(js, /workspace-group|group-head/);
  assert.match(js, /end_turn/);
  assert.match(js, /defaultModelId/);
  assert.match(js, /data-workspace-delete/);
  assert.ok(js.includes('/mobile/v1/workspaces/directories'));
  assert.match(js, /swipe-item/);
  assert.match(js, /data-session-action/);
  assert.match(js, /data-workspace-rename/);
  assert.match(js, /finalizeStreamingMessages/);
  assert.match(js, /data-retry/);
  assert.ok(js.includes('/mobile/v1/workspaces/directories/rename'));
  assert.match(css, /\.think\{[^}]*box-sizing:border-box[^}]*overflow:hidden/);
  assert.match(css, /\.think-body\{[^}]*min-width:0[^}]*max-width:100%[^}]*overflow-wrap:anywhere/);
  assert.match(css, /\.msg-body pre,.think-body pre\{[^}]*width:100%[^}]*box-sizing:border-box[^}]*overflow-x:auto/);
  assert.match(css, /\.msg-body code,.think-body code\{[^}]*overflow-wrap:anywhere/);

  assert.doesNotMatch(html, /<span>任务<\/span>/);
  assert.doesNotMatch(js, /finally\s*\{\s*\$\("#send"\)\.disabled\s*=\s*false;\s*input\.focus\(\)/);
  assert.match(js, /switchyard_mobile_event_cursor/);
  assert.match(js, /\/mobile\/v1\/approvals/);
  assert.match(js, /newAttachments/);
  assert.match(js, /renderMessageAttachments/);
  assert.match(js, /hydrateAttachmentPreviews/);
  assert.match(js, /\/mobile\/v1\/assets\//);
  assert.match(js, /data-attachment-open/);
  assert.match(js, /data-file-open/);
  assert.match(js, /data-decision="allow_once"/);
  assert.doesNotMatch(js, /必须回到桌面端确认/);
  assert.match(js, /\/mobile\/v1\/commands\?agent=/);
  assert.match(js, /function commandTrigger/);
  assert.match(js, /match\(\/\(\^\|\\s\)\(\[\/\$@\]\)/);
  assert.match(js, /trigger\.prefix === "@" \? item\.kind === "mention"/);
  assert.match(js, /agent === "codex" \? item\.kind === "command"/);
  assert.match(js, /function chooseCommand/);
  assert.match(js, /input\.setSelectionRange\(cursor, cursor\)/);
  assert.match(js, /commandPickerKeydown/);
  assert.match(html, /id="command-picker"/);
  assert.match(html, /id="message-mode-sheet"/);
  assert.match(html, /id="conversation-behavior-sheet"/);
  assert.match(html, /id="edit-pairing-link"/);
  assert.match(html, /更换配对链接/);
  assert.match(js, /nativePairingEditAvailable/);
  assert.match(js, /editPairingLink/);
  assert.match(html, /data-message-mode="guide"/);
  assert.match(html, /data-conversation-send-mode="ask"/);
  assert.match(js, /conversationSendMode/);
  assert.match(js, /PREFERENCES_KEY/);
  assert.match(js, /hasNativeTokenStore/);
  assert.match(js, /Android uses Keystore-backed storage/);
  assert.match(js, /isPreferencesEndpointUnavailable/);
  assert.match(js, /待桌面端升级后同步/);
  assert.match(js, /deliveryMode/);
  assert.match(js, /submitComposerMessage/);
  assert.match(css, /\.send-button\.is-stop/);
  assert.match(js, /function markdownTableCells/);
  assert.match(js, /const INTERNAL_UI_DIRECTIVE/);
  assert.match(js, /function stripInternalUiDirectives/);
  assert.match(js, /filter\(\(line\) => !INTERNAL_UI_DIRECTIVE\.test\(line\.trim\(\)\)\)/);
  assert.match(js, /const prose = stripInternalUiDirectives\(chunks\[i\] \|\| ""\)/);
  assert.match(html, /app\.js\?v=64/);
  assert.match(html, /styles\.css\?v=64/);
  assert.match(js, /function openSessionSwitcher/);
  assert.match(js, /sessionDetailCache/);
  assert.match(js, /INITIAL_MESSAGE_LIMIT = 120/);
  assert.match(js, /loadEarlierMessages/);
  assert.match(html, /id="approval-sheet"/);
  assert.match(html, /id="new-message-indicator"/);
  assert.match(html, /id="density-toggle"/);
  assert.match(js, /function renderApprovalSheet/);
  assert.match(js, /function renderNewMessageIndicator/);
  assert.match(js, /DENSITY_KEY/);
  assert.match(js, /data-turn-action/);
  assert.match(js, /data-diff-filter/);
  assert.match(css, /\.conversation-turn\{/);
  assert.match(css, /\.turn-completion\{/);
  assert.match(css, /\.new-message-indicator\{/);
  assert.match(html, /id="session-select-toggle"/);
  assert.match(html, /id="session-selection-bar"/);
  assert.match(html, /id="session-delete-sheet"/);
  assert.match(html, /id="stop-session-sheet"/);
  assert.match(html, /id="stop-session-name"/);
  assert.match(js, /function renderStopSessionSheet/);
  assert.match(js, /GROUP_STATE_KEY/);
  assert.match(js, /PINNED_PROJECTS_KEY/);
  assert.match(js, /data-open-active-sessions/);
  assert.match(js, /approval\.detail\?\.content/);
  assert.match(css, /\.approval-detail\{/);
  assert.match(js, /stopSessionQueueCount/);
  assert.match(css, /\.stop-session-sheet\{/);
  assert.match(html, /id="pull-to-refresh"/);
  assert.match(js, /function requestSessionDeletion/);
  assert.match(js, /function confirmSessionDeletion/);
  assert.match(js, /function refreshMobileData/);
  assert.match(js, /class="session-row\$\{sessionSelectionMode \? " selection-mode" : ""\} swipe-content"/);
  assert.match(js, /data-session-select/);
  assert.match(js, /sessionSelectionMode/);
  assert.match(css, /\.swipe-content\{[^}]*z-index:1[^}]*background:var\(--card\)/);
  assert.match(css, /\.session-selection-bar\{/);
  assert.match(css, /\.session-delete-sheet\{/);
  assert.match(css, /\.pull-to-refresh\{/);
  assert.match(js, /function createClientMessageId/);
  assert.match(js, /globalThis\.crypto\?\.randomUUID/);
  assert.match(js, /globalThis\.crypto\?\.getRandomValues/);
  assert.doesNotMatch(js, /messageId: crypto\.randomUUID/);
  assert.match(js, /function refreshSessionsInBackground/);
  assert.match(js, /data-switch-session/);
  assert.match(js, /function renderMarkdownTable/);
  assert.match(js, /function renderProducedFiles/);
  assert.match(js, /function renderDeliveredFile/);
  assert.match(js, /本轮交付/);
  assert.match(js, /asset\.source/);
  assert.match(js, /deliveryAt/);
  assert.match(js, /const MAX_ATTACHMENTS = 4/);
  assert.match(js, /const MAX_ATTACHMENT_BYTES = 8 \* 1024 \* 1024/);
  assert.match(js, /附件总大小不能超过 8MB/);
  assert.match(js, /本轮产物/);
  assert.match(js, /tool\.activity !== "edit"/);
  assert.match(css, /\.produced-files\{/);
  assert.match(js, /attachmentViewerHistoryOpen/);
  assert.match(js, /nativeAssetActionAvailable/);
  assert.match(js, /downloadAsset/);
  assert.match(js, /currentApproval/);
  assert.match(js, /switchyardAttachmentViewer/);
  assert.match(js, /window\.addEventListener\("popstate"/);
  assert.match(js, /closeAttachmentViewer\(\{ fromHistory: true \}\)/);
  assert.match(js, /markdown-table-wrap/);
  assert.match(css, /\.markdown-table-wrap\{/);
  assert.match(css, /\.markdown-table\{/);
  assert.match(css, /\.attachment-viewer-done\{/);
  assert.match(css, /\.attachment-viewer-actions\{/);
  assert.match(css, /\.attachment-viewer-open/);
  assert.match(css, /\.session-switcher-sheet\{/);
  assert.match(css, /\.continue-current-session\{/);
  assert.match(css, /\.command-picker\{/);
  assert.doesNotMatch(`${html}\n${js}`, /API Key|兼容包|Provider 配置|任意 Shell/);
  assert.match(js, /function setConnectionStatus/);
  assert.match(html, /id="detail-conn"/);
  assert.match(js, /function showInputSheet/);
  assert.match(js, /function closeInputSheet/);
  assert.match(html, /id="input-sheet"/);
  assert.doesNotMatch(js, /prompt\("编辑排队指令"|prompt\("会话名称"/);
  assert.match(js, /skel-msg/);
  assert.match(css, /\.skel\{/);
  assert.match(js, /distanceFromBottom/);
  assert.match(js, /visibilitychange/);
  assert.match(js, /LAST_TASK_KEY/);
  assert.match(js, /rememberLastTask/);
  assert.match(js, /data-open-session/);
  assert.match(css, /\.app-shell\[data-page="detail"\] \.tabbar\{display:none\}/);
  assert.match(css, /--muted:#8a8175/);
  assert.match(css, /\.session-row\[data-state="failed"\]::before\{background:var\(--danger\)\}/);
  assert.match(js, /THEME_KEY/);
  assert.match(js, /function applyTheme/);
  assert.match(html, /id="theme-toggle"/);
  assert.match(css, /:root\[data-theme="dark"\]\{/);
  assert.match(js, /nativeVoiceInputAvailable/);
  assert.match(js, /SwitchyardVoice/);
  assert.match(html, /id="voice-control"/);
  assert.match(js, /\/mobile\/v1\/sessions\/search\?q=/);
  assert.match(js, /function renderContentHits/);
  assert.match(js, /escapeRegExp/);
  assert.match(css, /\.content-hit\{/);
  assert.equal(manifest.display, "standalone");
});
