plugins {
  id 'com.android.application'
}

android {
  namespace 'com.zhangyinglong.switchyard'
  compileSdk 34

  defaultConfig {
    applicationId 'com.zhangyinglong.switchyard'
    minSdk 26
    targetSdk 34
    versionCode 4
    versionName '0.1.3'
  }

  buildTypes {
    debug {
      applicationIdSuffix '.debug'
      versionNameSuffix '-debug'
    }
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
}
